import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAmericas,
  HiOutlineRocketLaunch,
  HiOutlineBriefcase,
  HiOutlineInformationCircle,
  HiOutlineChatBubbleLeftRight,
  HiOutlineCurrencyDollar,
  HiOutlineShieldCheck,
  HiOutlineUserGroup,
  HiOutlineHeart,
  HiOutlinePhone,
  HiOutlineMapPin,
  HiOutlineClock,
  HiOutlineCheckCircle,
  HiOutlineCloudArrowUp,
  HiOutlinePaperAirplane,
  HiOutlineCodeBracket,
  HiOutlineAcademicCap,
  HiOutlineSparkles,
  HiOutlineLockClosed,
} from "react-icons/hi2";

import { PiHouseDuotone, PiBookBookmarkDuotone, PiCompassDuotone } from "react-icons/pi";

import {
  FaGithub,
  FaLinkedin,
  FaX,
  FaXTwitter,
  FaFacebook,
  FaInstagram,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  openLink: HiOutlineLink,
  email: HiEnvelope,
  phone: HiOutlinePhone,
  location: HiOutlineMapPin,
  clock: HiOutlineClock,
  calendar: HiCalendarDays,
  globe: HiOutlineGlobeAmericas,
  home: PiHouseDuotone,
  info: HiOutlineInformationCircle,
  briefcase: HiOutlineBriefcase,
  book: PiBookBookmarkDuotone,
  chat: HiOutlineChatBubbleLeftRight,
  compass: PiCompassDuotone,
  dollar: HiOutlineCurrencyDollar,
  shield: HiOutlineShieldCheck,
  users: HiOutlineUserGroup,
  heart: HiOutlineHeart,
  check: HiOutlineCheckCircle,
  upload: HiOutlineCloudArrowUp,
  send: HiOutlinePaperAirplane,
  code: HiOutlineCodeBracket,
  academic: HiOutlineAcademicCap,
  sparkles: HiOutlineSparkles,
  lock: HiOutlineLockClosed,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  facebook: FaFacebook,
  instagram: FaInstagram,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
